# -*- coding: utf-8 -*-
"""2018112801_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Jh1O1M8YMQph9sJKDJFjXg6VYQ1Yin-
"""

#2. 당신 생일을 변수 월(bmonth)과 일(bday)로 저장하고 
#다음과 같이 곱하기, 나누기, 더하기, 빼기한 결과를 출력하세요. (0 또는 음수가 나올 수 있습니다.)

bmonth=1
bday=29

print(bmonth * bday)
print(bmonth / bday)
print(bmonth + bday)
print(bmonth - bday)

