# -*- coding: utf-8 -*-
"""2018112801_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17NT14nT-pcdb9OjpwEFDsl-5WkJIwys3
"""

#3. 지난 학기 수강한 5개 과목 점수를 변수로 저장하고 평점(소수점 2자리까지)을 구하세요.

myscore_lib1104 = 4.3
myscore_lib1105 = 4.15
myscore_lib1106 = 4.0
myscore_lib1108 = 2.75 
myscore_lib1109 = 3.5

average= (myscore_lib1104+myscore_lib1105+myscore_lib1106+myscore_lib1108+myscore_lib1109)/5

print('평점 : %.2f'%average)

