# -*- coding: utf-8 -*-
"""2018112801_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zf5eaoGc69wqiMu4sfUs5YK1to_b_3mh
"""

#1. 당신의 이름을 변수로 저장하고 당신에게 보내는 인사말을 출력하세요.
name="Dongjae"

print("Hi,"+name+"! It's good to see you in this class!")

